name: Build Chrome Extension

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r extension.zip . \
            -x ".git/*" \
               ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: extension.zip